site_name: "Zhōngguó II"

docs_dir: pages_build

nav:
  - Home: https://robin.ar
  - Índice: index.md
  - Capítulos:
    - I: I.md
    - II: II.md
    - III: III.md
    - IV: IV.md
    - V: V.md
    - VI: VI.md
    - VII: VII.md
    - VIII: VIII.md
    - IX: IX.md
    - X: X.md

theme:
  name: material
  font:
    text: "Merriweather"
    code: "Noto Sans Traditional Chinese"
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - navigation.autohide
    - content.code.annotate
    - content.tooltips
    - header.autohide
    - toc.integrate


extra_css:
  - styles/novel.css

extra_javascript:
  - styles/novel.js

extra:
  generator: false
  javascripts:
    - https://fonts.googleapis.com/css2?family=VT323&display=swap
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: zii
          class: language-zii
  - pymdownx.highlight:
      use_pygments: false
